// JLPT N5 Grammar — Full 80 Points
const GRAMMAR_FULL = [
    // Week 1 — Basics & Existence
    { pattern: "〜は〜です", meaning: "A is B (copula)", example: "わたし は がくせい です", translation: "I am a student.", week: 1 },
    { pattern: "〜は〜じゃないです", meaning: "A is not B (negative copula)", example: "これ は ほん じゃないです", translation: "This is not a book.", week: 1 },
    { pattern: "〜は〜でした", meaning: "A was B (past copula)", example: "きのう は にちようび でした", translation: "Yesterday was Sunday.", week: 1 },
    { pattern: "〜は〜じゃなかったです", meaning: "A was not B (past neg. copula)", example: "やすみ じゃなかったです", translation: "It wasn't a holiday.", week: 1 },
    { pattern: "〜の〜", meaning: "Possessive / descriptive connector", example: "わたし の ほん", translation: "My book", week: 1 },
    { pattern: "〜か", meaning: "Question marker", example: "がくせい ですか", translation: "Are you a student?", week: 1 },
    { pattern: "〜も", meaning: "Also / Too (replaces は/が/を)", example: "わたし も がくせい です", translation: "I am also a student.", week: 1 },
    { pattern: "これ/それ/あれ", meaning: "This / That / That over there", example: "これ は なん ですか", translation: "What is this?", week: 1 },
    { pattern: "この/その/あの + Noun", meaning: "This~/That~/That~ + noun modifier", example: "この ほん は おもしろい です", translation: "This book is interesting.", week: 1 },
    { pattern: "ここ/そこ/あそこ", meaning: "Here / There / Over there (place)", example: "トイレ は あそこ です", translation: "The toilet is over there.", week: 1 },
    { pattern: "〜に〜があります", meaning: "There is ~ (inanimate) at ~", example: "つくえ の うえ に ほん が あります", translation: "There is a book on the desk.", week: 1 },
    { pattern: "〜に〜がいます", meaning: "There is ~ (animate) at ~", example: "こうえん に こども が います", translation: "There are children in the park.", week: 1 },
    { pattern: "が (subject marker)", meaning: "Marks the subject / new information", example: "だれ が きましたか", translation: "Who came?", week: 1 },
    { pattern: "〜と〜", meaning: "A and B (exhaustive list)", example: "パン と たまご", translation: "Bread and egg.", week: 1 },
    { pattern: "〜や〜(など)", meaning: "A and B (and so on, non-exhaustive)", example: "りんご や みかん など", translation: "Apples, oranges, etc.", week: 1 },
    // Week 2 — Verb Conjugation & Movement
    { pattern: "〜を〜ます", meaning: "Object + polite present/future verb", example: "みず を のみます", translation: "I drink water.", week: 2 },
    { pattern: "〜ません", meaning: "Polite negative verb", example: "にく を たべません", translation: "I don't eat meat.", week: 2 },
    { pattern: "〜ました", meaning: "Polite past verb", example: "ほん を よみました", translation: "I read a book.", week: 2 },
    { pattern: "〜ませんでした", meaning: "Polite past negative verb", example: "テレビ を みませんでした", translation: "I didn't watch TV.", week: 2 },
    { pattern: "〜に いきます (destination)", meaning: "Go to ~ (destination particle)", example: "がっこう に いきます", translation: "I go to school.", week: 2 },
    { pattern: "〜へ いきます (direction)", meaning: "Go toward ~ (direction particle)", example: "にほん へ いきます", translation: "I go to Japan.", week: 2 },
    { pattern: "〜で (means/tools)", meaning: "By means of / using", example: "バス で いきます", translation: "I go by bus.", week: 2 },
    { pattern: "〜で (location of action)", meaning: "At ~ (where action happens)", example: "としょかん で べんきょうします", translation: "I study at the library.", week: 2 },
    { pattern: "〜に (time)", meaning: "At ~ (specific time point)", example: "しちじ に おきます", translation: "I wake up at 7:00.", week: 2 },
    { pattern: "〜から〜まで (range)", meaning: "From ~ to/until ~", example: "くじ から ごじ まで はたらきます", translation: "I work from 9 to 5.", week: 2 },
    { pattern: "〜ましょう", meaning: "Let's ~ (suggestion)", example: "ひるごはん を たべましょう", translation: "Let's eat lunch.", week: 2 },
    { pattern: "〜ませんか", meaning: "Won't you ~? (polite invitation)", example: "いっしょに いきませんか", translation: "Won't you go together?", week: 2 },
    { pattern: "〜てください", meaning: "Please do ~ (polite request)", example: "ここに すわってください", translation: "Please sit here.", week: 2 },
    { pattern: "〜ています (progressive)", meaning: "Is doing ~ / State of ~", example: "いま ほん を よんでいます", translation: "I am reading a book now.", week: 2 },
    { pattern: "〜て (sequential actions)", meaning: "Do A, then do B (connective)", example: "あさ おきて、ごはん を たべます", translation: "I wake up and eat breakfast.", week: 2 },
    { pattern: "Verb に いきます (purpose)", meaning: "Go to do ~ (purpose of movement)", example: "えいが を み に いきます", translation: "I go to watch a movie.", week: 2 },
    { pattern: "〜と (with person)", meaning: "With ~ (companion)", example: "ともだち と はなします", translation: "I talk with a friend.", week: 2 },
    // Week 3 — Adjectives, Questions, Desire
    { pattern: "い-adj present negative", meaning: "Drop い, add くない", example: "たかくない です", translation: "It's not expensive.", week: 3 },
    { pattern: "い-adj past affirmative", meaning: "Drop い, add かった", example: "たのしかった です", translation: "It was fun.", week: 3 },
    { pattern: "い-adj past negative", meaning: "Drop い, add くなかった", example: "おいしくなかった です", translation: "It wasn't delicious.", week: 3 },
    { pattern: "いい → よくない/よかった", meaning: "Special conjugation of いい (good)", example: "きのう の テスト は よくなかった です", translation: "Yesterday's test wasn't good.", week: 3 },
    { pattern: "な-adj + な + Noun", meaning: "Na-adj modifying a noun", example: "きれい な ひと", translation: "A beautiful person.", week: 3 },
    { pattern: "な-adj + です", meaning: "Na-adj predicate", example: "この まち は しずか です", translation: "This town is quiet.", week: 3 },
    { pattern: "な-adj + じゃないです", meaning: "Na-adj negative", example: "げんき じゃないです", translation: "I'm not well.", week: 3 },
    { pattern: "な-adj + でした / じゃなかったです", meaning: "Na-adj past / past negative", example: "しずか でした", translation: "It was quiet.", week: 3 },
    { pattern: "どこ/だれ/いつ/なに", meaning: "Where / Who / When / What", example: "えき は どこ ですか", translation: "Where is the station?", week: 3 },
    { pattern: "どう / いかが", meaning: "How (opinion/state)", example: "にほん は どう ですか", translation: "How is Japan?", week: 3 },
    { pattern: "どうして / なぜ", meaning: "Why", example: "どうして にほんご を べんきょうしますか", translation: "Why do you study Japanese?", week: 3 },
    { pattern: "どのくらい / どれくらい", meaning: "How long / How much (extent)", example: "えき まで どのくらい かかりますか", translation: "How long to the station?", week: 3 },
    { pattern: "なんで (means)", meaning: "By what means", example: "なんで きましたか", translation: "How did you come? (By what?)", week: 3 },
    { pattern: "〜たい です", meaning: "Want to do ~ (1st person desire)", example: "にほん に いきたい です", translation: "I want to go to Japan.", week: 3 },
    { pattern: "〜たくない です", meaning: "Don't want to do ~", example: "べんきょうしたくない です", translation: "I don't want to study.", week: 3 },
    { pattern: "〜がほしい です", meaning: "Want ~ (noun, 1st person)", example: "あたらしい くるま が ほしい です", translation: "I want a new car.", week: 3 },
    { pattern: "〜たことがあります", meaning: "Have experienced / done ~ before", example: "すし を たべたことがあります", translation: "I have eaten sushi before.", week: 3 },
    { pattern: "A のほうが B より〜", meaning: "A is more ~ than B", example: "にほんご のほうが えいご より むずかしいです", translation: "Japanese is harder than English.", week: 3 },
    { pattern: "〜がいちばん〜", meaning: "~ is the most ~ (superlative)", example: "すし が いちばん おいしいです", translation: "Sushi is the most delicious.", week: 3 },
    { pattern: "A と B と どちら", meaning: "Which one, A or B?", example: "やま と うみ と、どちらが すきですか", translation: "Mountains or sea, which do you like?", week: 3 },
    { pattern: "〜つ / 〜人 / 〜本 / 〜枚", meaning: "Counter suffixes (general/people/long/flat)", example: "りんご を みっつ ください", translation: "Three apples please.", week: 3 },
    { pattern: "Noun が じょうず/へた です", meaning: "Good at / Bad at ~", example: "にほんご が じょうず です", translation: "You are good at Japanese.", week: 3 },
    { pattern: "Noun が すき/きらい です", meaning: "Like / Dislike ~", example: "おんがく が すき です", translation: "I like music.", week: 3 },
    // Week 4 — Connectors, Permission, Obligation, Review
    { pattern: "〜から (reason)", meaning: "Because ~ / So ~", example: "あつい から まど を あけます", translation: "Because it's hot, I open the window.", week: 4 },
    { pattern: "〜けど / 〜が (contrast)", meaning: "But / Although", example: "むずかしい けど たのしい です", translation: "It's difficult but fun.", week: 4 },
    { pattern: "〜とき", meaning: "When ~ / At the time of ~", example: "ひま な とき、ほん を よみます", translation: "When I'm free, I read books.", week: 4 },
    { pattern: "〜まえに", meaning: "Before doing ~", example: "ねる まえに はをみがきます", translation: "Before sleeping, I brush teeth.", week: 4 },
    { pattern: "〜あとで", meaning: "After doing ~", example: "ごはん の あとで さんぽします", translation: "After eating, I take a walk.", week: 4 },
    { pattern: "〜てもいいです(か)", meaning: "May I ~? / It's okay to ~", example: "しゃしん を とってもいいですか", translation: "May I take a photo?", week: 4 },
    { pattern: "〜てはいけません", meaning: "Must not ~ (prohibition)", example: "ここ で たべてはいけません", translation: "You must not eat here.", week: 4 },
    { pattern: "〜なければなりません", meaning: "Must do ~ / Have to ~", example: "しゅくだい を しなければなりません", translation: "I must do homework.", week: 4 },
    { pattern: "〜なくてもいいです", meaning: "Don't have to ~ (no obligation)", example: "あした こなくてもいいです", translation: "You don't have to come tomorrow.", week: 4 },
    { pattern: "〜ないでください", meaning: "Please don't do ~", example: "ここ で たべないでください", translation: "Please don't eat here.", week: 4 },
    { pattern: "〜と おもいます", meaning: "I think that ~", example: "あした あめ だ と おもいます", translation: "I think it will rain tomorrow.", week: 4 },
    { pattern: "〜と いいます", meaning: "It is called ~ / ~ says", example: "これ は にほんご で なんと いいますか", translation: "What is this called in Japanese?", week: 4 },
    { pattern: "〜でしょう", meaning: "Probably ~ / I suppose ~", example: "あした は いい てんき でしょう", translation: "Tomorrow will probably be nice.", week: 4 },
    { pattern: "〜ながら", meaning: "While doing ~ (simultaneous)", example: "おんがく を ききながら べんきょうします", translation: "I study while listening to music.", week: 4 },
    { pattern: "〜てから", meaning: "After doing ~ (then)", example: "ごはん を たべてから でかけます", translation: "After eating, I go out.", week: 4 },
    { pattern: "まだ〜ていません", meaning: "Haven't done ~ yet", example: "まだ しゅくだい を していません", translation: "I haven't done homework yet.", week: 4 },
    { pattern: "もう〜ました", meaning: "Already did ~", example: "もう ひるごはん を たべました", translation: "I already ate lunch.", week: 4 },
    { pattern: "〜すぎます", meaning: "Too much ~ (excessive)", example: "このかばんは おもすぎます", translation: "This bag is too heavy.", week: 4 },
    { pattern: "〜は〜が〜", meaning: "Topic has attribute (double subject)", example: "ぞうは はなが ながいです", translation: "Elephants have long noses.", week: 4 },
    { pattern: "〜のがすきです", meaning: "Like doing ~ (verb nominalization)", example: "うたうのが すきです", translation: "I like singing.", week: 4 },
    { pattern: "〜のがじょうずです", meaning: "Good at doing ~", example: "りょうりするのが じょうずです", translation: "Good at cooking.", week: 4 },
    { pattern: "あげる/もらう/くれる", meaning: "Give / Receive / Give (to me)", example: "ともだちに ほんを あげました", translation: "I gave a book to my friend.", week: 4 },
    { pattern: "Noun に する", meaning: "Decide on ~ / Choose ~", example: "コーヒー に します", translation: "I'll have coffee. (I'll go with coffee)", week: 4 },
    { pattern: "〜そうです (hearsay)", meaning: "I heard that ~ / They say ~", example: "あした あめ だそうです", translation: "I heard it will rain tomorrow.", week: 4 },
];
