// JLPT N5 Vocabulary — Part 1: Nouns (People, Family, Body, Nature, Time)
const VOCAB_NOUNS_1 = [
    // People & Family
    { jp: "わたし", reading: "私", en: "I / Me", cat: "People" },
    { jp: "あなた", reading: "", en: "You", cat: "People" },
    { jp: "かれ", reading: "彼", en: "He / Him / Boyfriend", cat: "People" },
    { jp: "かのじょ", reading: "彼女", en: "She / Her / Girlfriend", cat: "People" },
    { jp: "わたしたち", reading: "私たち", en: "We / Us", cat: "People" },
    { jp: "ひと", reading: "人", en: "Person", cat: "People" },
    { jp: "こども", reading: "子供", en: "Child", cat: "People" },
    { jp: "おとこ", reading: "男", en: "Man / Male", cat: "People" },
    { jp: "おとこのこ", reading: "男の子", en: "Boy", cat: "People" },
    { jp: "おんな", reading: "女", en: "Woman / Female", cat: "People" },
    { jp: "おんなのこ", reading: "女の子", en: "Girl", cat: "People" },
    { jp: "おとな", reading: "大人", en: "Adult", cat: "People" },
    { jp: "ともだち", reading: "友達", en: "Friend", cat: "People" },
    { jp: "せんせい", reading: "先生", en: "Teacher / Doctor (title)", cat: "People" },
    { jp: "がくせい", reading: "学生", en: "Student", cat: "People" },
    { jp: "りゅうがくせい", reading: "留学生", en: "Exchange student", cat: "People" },
    { jp: "かいしゃいん", reading: "会社員", en: "Company employee", cat: "People" },
    { jp: "いしゃ", reading: "医者", en: "Doctor", cat: "People" },
    { jp: "けいさつ", reading: "警察", en: "Police", cat: "People" },
    // Family
    { jp: "かぞく", reading: "家族", en: "Family", cat: "Family" },
    { jp: "りょうしん", reading: "両親", en: "Parents", cat: "Family" },
    { jp: "ちち", reading: "父", en: "Father (humble)", cat: "Family" },
    { jp: "おとうさん", reading: "お父さん", en: "Father (polite)", cat: "Family" },
    { jp: "はは", reading: "母", en: "Mother (humble)", cat: "Family" },
    { jp: "おかあさん", reading: "お母さん", en: "Mother (polite)", cat: "Family" },
    { jp: "あに", reading: "兄", en: "Older brother (humble)", cat: "Family" },
    { jp: "おにいさん", reading: "お兄さん", en: "Older brother (polite)", cat: "Family" },
    { jp: "あね", reading: "姉", en: "Older sister (humble)", cat: "Family" },
    { jp: "おねえさん", reading: "お姉さん", en: "Older sister (polite)", cat: "Family" },
    { jp: "おとうと", reading: "弟", en: "Younger brother", cat: "Family" },
    { jp: "いもうと", reading: "妹", en: "Younger sister", cat: "Family" },
    { jp: "おじいさん", reading: "", en: "Grandfather / Old man", cat: "Family" },
    { jp: "おばあさん", reading: "", en: "Grandmother / Old woman", cat: "Family" },
    { jp: "しゅじん", reading: "主人", en: "Husband (humble)", cat: "Family" },
    { jp: "おくさん", reading: "奥さん", en: "Wife (polite)", cat: "Family" },
    { jp: "きょうだい", reading: "兄弟", en: "Siblings", cat: "Family" },
    // Body
    { jp: "あたま", reading: "頭", en: "Head", cat: "Body" },
    { jp: "かみ", reading: "髪", en: "Hair", cat: "Body" },
    { jp: "かお", reading: "顔", en: "Face", cat: "Body" },
    { jp: "め", reading: "目", en: "Eye", cat: "Body" },
    { jp: "みみ", reading: "耳", en: "Ear", cat: "Body" },
    { jp: "はな", reading: "鼻", en: "Nose", cat: "Body" },
    { jp: "くち", reading: "口", en: "Mouth", cat: "Body" },
    { jp: "は", reading: "歯", en: "Tooth / Teeth", cat: "Body" },
    { jp: "て", reading: "手", en: "Hand", cat: "Body" },
    { jp: "ゆび", reading: "指", en: "Finger", cat: "Body" },
    { jp: "あし", reading: "足", en: "Foot / Leg", cat: "Body" },
    { jp: "おなか", reading: "お腹", en: "Stomach / Belly", cat: "Body" },
    { jp: "せ", reading: "背", en: "Back / Height", cat: "Body" },
    { jp: "からだ", reading: "体", en: "Body", cat: "Body" },
    // Nature & Weather
    { jp: "そら", reading: "空", en: "Sky", cat: "Nature" },
    { jp: "やま", reading: "山", en: "Mountain", cat: "Nature" },
    { jp: "かわ", reading: "川", en: "River", cat: "Nature" },
    { jp: "うみ", reading: "海", en: "Sea / Ocean", cat: "Nature" },
    { jp: "はな", reading: "花", en: "Flower", cat: "Nature" },
    { jp: "き", reading: "木", en: "Tree", cat: "Nature" },
    { jp: "もり", reading: "森", en: "Forest", cat: "Nature" },
    { jp: "いけ", reading: "池", en: "Pond", cat: "Nature" },
    { jp: "てんき", reading: "天気", en: "Weather", cat: "Nature" },
    { jp: "あめ", reading: "雨", en: "Rain", cat: "Nature" },
    { jp: "ゆき", reading: "雪", en: "Snow", cat: "Nature" },
    { jp: "かぜ", reading: "風", en: "Wind", cat: "Nature" },
    { jp: "くもり", reading: "曇り", en: "Cloudy", cat: "Nature" },
    { jp: "はれ", reading: "晴れ", en: "Sunny / Clear weather", cat: "Nature" },
    // Time
    { jp: "いま", reading: "今", en: "Now", cat: "Time" },
    { jp: "きょう", reading: "今日", en: "Today", cat: "Time" },
    { jp: "あした", reading: "明日", en: "Tomorrow", cat: "Time" },
    { jp: "あさって", reading: "明後日", en: "Day after tomorrow", cat: "Time" },
    { jp: "きのう", reading: "昨日", en: "Yesterday", cat: "Time" },
    { jp: "おととい", reading: "一昨日", en: "Day before yesterday", cat: "Time" },
    { jp: "あさ", reading: "朝", en: "Morning", cat: "Time" },
    { jp: "ひる", reading: "昼", en: "Noon / Daytime", cat: "Time" },
    { jp: "ゆうがた", reading: "夕方", en: "Evening (early)", cat: "Time" },
    { jp: "よる", reading: "夜", en: "Night", cat: "Time" },
    { jp: "ばん", reading: "晩", en: "Night / Evening", cat: "Time" },
    { jp: "まいにち", reading: "毎日", en: "Every day", cat: "Time" },
    { jp: "まいあさ", reading: "毎朝", en: "Every morning", cat: "Time" },
    { jp: "まいばん", reading: "毎晩", en: "Every night", cat: "Time" },
    { jp: "まいしゅう", reading: "毎週", en: "Every week", cat: "Time" },
    { jp: "まいつき", reading: "毎月", en: "Every month", cat: "Time" },
    { jp: "まいとし", reading: "毎年", en: "Every year", cat: "Time" },
    { jp: "こんしゅう", reading: "今週", en: "This week", cat: "Time" },
    { jp: "らいしゅう", reading: "来週", en: "Next week", cat: "Time" },
    { jp: "せんしゅう", reading: "先週", en: "Last week", cat: "Time" },
    { jp: "こんげつ", reading: "今月", en: "This month", cat: "Time" },
    { jp: "らいげつ", reading: "来月", en: "Next month", cat: "Time" },
    { jp: "せんげつ", reading: "先月", en: "Last month", cat: "Time" },
    { jp: "ことし", reading: "今年", en: "This year", cat: "Time" },
    { jp: "らいねん", reading: "来年", en: "Next year", cat: "Time" },
    { jp: "きょねん", reading: "去年", en: "Last year", cat: "Time" },
    { jp: "じかん", reading: "時間", en: "Time / Hours", cat: "Time" },
    { jp: "はん", reading: "半", en: "Half (e.g. 3:30)", cat: "Time" },
    { jp: "ごぜん", reading: "午前", en: "AM / Morning", cat: "Time" },
    { jp: "ごご", reading: "午後", en: "PM / Afternoon", cat: "Time" },
    // Days of week
    { jp: "げつようび", reading: "月曜日", en: "Monday", cat: "Days" },
    { jp: "かようび", reading: "火曜日", en: "Tuesday", cat: "Days" },
    { jp: "すいようび", reading: "水曜日", en: "Wednesday", cat: "Days" },
    { jp: "もくようび", reading: "木曜日", en: "Thursday", cat: "Days" },
    { jp: "きんようび", reading: "金曜日", en: "Friday", cat: "Days" },
    { jp: "どようび", reading: "土曜日", en: "Saturday", cat: "Days" },
    { jp: "にちようび", reading: "日曜日", en: "Sunday", cat: "Days" },
    { jp: "しゅうまつ", reading: "週末", en: "Weekend", cat: "Days" },
    // Months (ordinal)
    { jp: "いちがつ", reading: "一月", en: "January", cat: "Months" },
    { jp: "にがつ", reading: "二月", en: "February", cat: "Months" },
    { jp: "さんがつ", reading: "三月", en: "March", cat: "Months" },
    { jp: "しがつ", reading: "四月", en: "April", cat: "Months" },
    { jp: "ごがつ", reading: "五月", en: "May", cat: "Months" },
    { jp: "ろくがつ", reading: "六月", en: "June", cat: "Months" },
    { jp: "しちがつ", reading: "七月", en: "July", cat: "Months" },
    { jp: "はちがつ", reading: "八月", en: "August", cat: "Months" },
    { jp: "くがつ", reading: "九月", en: "September", cat: "Months" },
    { jp: "じゅうがつ", reading: "十月", en: "October", cat: "Months" },
    { jp: "じゅういちがつ", reading: "十一月", en: "November", cat: "Months" },
    { jp: "じゅうにがつ", reading: "十二月", en: "December", cat: "Months" },
];
