// JLPT N5 Vocabulary — Part 2: Nouns (Places, School, Food, Drink, House)
const VOCAB_NOUNS_2 = [
    // Places & Buildings
    { jp: "がっこう", reading: "学校", en: "School", cat: "Places" },
    { jp: "だいがく", reading: "大学", en: "University", cat: "Places" },
    { jp: "びょういん", reading: "病院", en: "Hospital", cat: "Places" },
    { jp: "えき", reading: "駅", en: "Station", cat: "Places" },
    { jp: "としょかん", reading: "図書館", en: "Library", cat: "Places" },
    { jp: "ゆうびんきょく", reading: "郵便局", en: "Post office", cat: "Places" },
    { jp: "ぎんこう", reading: "銀行", en: "Bank", cat: "Places" },
    { jp: "みせ", reading: "店", en: "Shop / Store", cat: "Places" },
    { jp: "レストラン", reading: "", en: "Restaurant", cat: "Places" },
    { jp: "デパート", reading: "", en: "Department store", cat: "Places" },
    { jp: "スーパー", reading: "", en: "Supermarket", cat: "Places" },
    { jp: "こうえん", reading: "公園", en: "Park", cat: "Places" },
    { jp: "ホテル", reading: "", en: "Hotel", cat: "Places" },
    { jp: "かいしゃ", reading: "会社", en: "Company / Office", cat: "Places" },
    { jp: "こうばん", reading: "交番", en: "Police box", cat: "Places" },
    { jp: "たいしかん", reading: "大使館", en: "Embassy", cat: "Places" },
    { jp: "プール", reading: "", en: "Pool", cat: "Places" },
    { jp: "えいがかん", reading: "映画館", en: "Cinema", cat: "Places" },
    { jp: "きっさてん", reading: "喫茶店", en: "Cafe / Coffee shop", cat: "Places" },
    { jp: "しょくどう", reading: "食堂", en: "Cafeteria / Dining hall", cat: "Places" },
    { jp: "くうこう", reading: "空港", en: "Airport", cat: "Places" },
    { jp: "まち", reading: "町", en: "Town / City", cat: "Places" },
    { jp: "むら", reading: "村", en: "Village", cat: "Places" },
    { jp: "くに", reading: "国", en: "Country", cat: "Places" },
    // School & Study
    { jp: "きょうしつ", reading: "教室", en: "Classroom", cat: "School" },
    { jp: "じゅぎょう", reading: "授業", en: "Class / Lesson", cat: "School" },
    { jp: "しゅくだい", reading: "宿題", en: "Homework", cat: "School" },
    { jp: "テスト", reading: "", en: "Test / Exam", cat: "School" },
    { jp: "しけん", reading: "試験", en: "Examination", cat: "School" },
    { jp: "もんだい", reading: "問題", en: "Problem / Question", cat: "School" },
    { jp: "こたえ", reading: "答え", en: "Answer", cat: "School" },
    { jp: "しつもん", reading: "質問", en: "Question", cat: "School" },
    { jp: "ほん", reading: "本", en: "Book", cat: "School" },
    { jp: "じしょ", reading: "辞書", en: "Dictionary", cat: "School" },
    { jp: "ノート", reading: "", en: "Notebook", cat: "School" },
    { jp: "えんぴつ", reading: "鉛筆", en: "Pencil", cat: "School" },
    { jp: "ペン", reading: "", en: "Pen", cat: "School" },
    { jp: "ボールペン", reading: "", en: "Ball-point pen", cat: "School" },
    { jp: "けしゴム", reading: "消しゴム", en: "Eraser", cat: "School" },
    { jp: "かみ", reading: "紙", en: "Paper", cat: "School" },
    { jp: "かばん", reading: "", en: "Bag / Briefcase", cat: "School" },
    { jp: "ざっし", reading: "雑誌", en: "Magazine", cat: "School" },
    { jp: "しんぶん", reading: "新聞", en: "Newspaper", cat: "School" },
    { jp: "ことば", reading: "言葉", en: "Word / Language", cat: "School" },
    { jp: "ぶんしょう", reading: "文章", en: "Sentence / Text", cat: "School" },
    { jp: "いみ", reading: "意味", en: "Meaning", cat: "School" },
    { jp: "にほんご", reading: "日本語", en: "Japanese (language)", cat: "School" },
    { jp: "えいご", reading: "英語", en: "English (language)", cat: "School" },
    { jp: "べんきょう", reading: "勉強", en: "Study", cat: "School" },
    { jp: "れんしゅう", reading: "練習", en: "Practice", cat: "School" },
    // Food & Drink
    { jp: "ごはん", reading: "ご飯", en: "Rice / Meal", cat: "Food" },
    { jp: "パン", reading: "", en: "Bread", cat: "Food" },
    { jp: "たまご", reading: "卵", en: "Egg", cat: "Food" },
    { jp: "にく", reading: "肉", en: "Meat", cat: "Food" },
    { jp: "とりにく", reading: "鶏肉", en: "Chicken meat", cat: "Food" },
    { jp: "ぶたにく", reading: "豚肉", en: "Pork", cat: "Food" },
    { jp: "ぎゅうにく", reading: "牛肉", en: "Beef", cat: "Food" },
    { jp: "さかな", reading: "魚", en: "Fish", cat: "Food" },
    { jp: "やさい", reading: "野菜", en: "Vegetables", cat: "Food" },
    { jp: "くだもの", reading: "果物", en: "Fruit", cat: "Food" },
    { jp: "りんご", reading: "", en: "Apple", cat: "Food" },
    { jp: "みかん", reading: "", en: "Mandarin orange", cat: "Food" },
    { jp: "さとう", reading: "砂糖", en: "Sugar", cat: "Food" },
    { jp: "しお", reading: "塩", en: "Salt", cat: "Food" },
    { jp: "しょうゆ", reading: "醤油", en: "Soy sauce", cat: "Food" },
    { jp: "おかし", reading: "お菓子", en: "Sweets / Snacks", cat: "Food" },
    { jp: "ケーキ", reading: "", en: "Cake", cat: "Food" },
    { jp: "すし", reading: "寿司", en: "Sushi", cat: "Food" },
    { jp: "てんぷら", reading: "天ぷら", en: "Tempura", cat: "Food" },
    { jp: "おべんとう", reading: "お弁当", en: "Lunch box / Bento", cat: "Food" },
    { jp: "あさごはん", reading: "朝ご飯", en: "Breakfast", cat: "Food" },
    { jp: "ひるごはん", reading: "昼ご飯", en: "Lunch", cat: "Food" },
    { jp: "ばんごはん", reading: "晩ご飯", en: "Dinner", cat: "Food" },
    { jp: "りょうり", reading: "料理", en: "Cooking / Cuisine", cat: "Food" },
    // Drinks
    { jp: "みず", reading: "水", en: "Water", cat: "Drinks" },
    { jp: "おちゃ", reading: "お茶", en: "Tea (green)", cat: "Drinks" },
    { jp: "こうちゃ", reading: "紅茶", en: "Black tea", cat: "Drinks" },
    { jp: "コーヒー", reading: "", en: "Coffee", cat: "Drinks" },
    { jp: "ぎゅうにゅう", reading: "牛乳", en: "Milk", cat: "Drinks" },
    { jp: "ジュース", reading: "", en: "Juice", cat: "Drinks" },
    { jp: "おさけ", reading: "お酒", en: "Alcohol / Sake", cat: "Drinks" },
    { jp: "ビール", reading: "", en: "Beer", cat: "Drinks" },
    // House & Home
    { jp: "うち", reading: "", en: "Home / House (own)", cat: "House" },
    { jp: "いえ", reading: "家", en: "House / Home", cat: "House" },
    { jp: "アパート", reading: "", en: "Apartment", cat: "House" },
    { jp: "へや", reading: "部屋", en: "Room", cat: "House" },
    { jp: "だいどころ", reading: "台所", en: "Kitchen", cat: "House" },
    { jp: "おふろ", reading: "お風呂", en: "Bath / Bathroom", cat: "House" },
    { jp: "トイレ", reading: "", en: "Toilet / Restroom", cat: "House" },
    { jp: "にわ", reading: "庭", en: "Garden", cat: "House" },
    { jp: "げんかん", reading: "玄関", en: "Entrance / Front door", cat: "House" },
    { jp: "まど", reading: "窓", en: "Window", cat: "House" },
    { jp: "ドア", reading: "", en: "Door", cat: "House" },
    { jp: "いす", reading: "椅子", en: "Chair", cat: "House" },
    { jp: "つくえ", reading: "机", en: "Desk", cat: "House" },
    { jp: "テーブル", reading: "", en: "Table", cat: "House" },
    { jp: "ベッド", reading: "", en: "Bed", cat: "House" },
    { jp: "たな", reading: "棚", en: "Shelf", cat: "House" },
    { jp: "でんき", reading: "電気", en: "Light / Electricity", cat: "House" },
    { jp: "エアコン", reading: "", en: "Air conditioner", cat: "House" },
    { jp: "れいぞうこ", reading: "冷蔵庫", en: "Refrigerator", cat: "House" },
    { jp: "せんたくき", reading: "洗濯機", en: "Washing machine", cat: "House" },
];
