// JLPT N5 Vocabulary — Part 3: Nouns (Transport, Daily Items, Clothes, Colors, Countries, Misc)
const VOCAB_NOUNS_3 = [
    // Transport
    { jp: "くるま", reading: "車", en: "Car", cat: "Transport" },
    { jp: "でんしゃ", reading: "電車", en: "Train", cat: "Transport" },
    { jp: "バス", reading: "", en: "Bus", cat: "Transport" },
    { jp: "タクシー", reading: "", en: "Taxi", cat: "Transport" },
    { jp: "じてんしゃ", reading: "自転車", en: "Bicycle", cat: "Transport" },
    { jp: "ひこうき", reading: "飛行機", en: "Airplane", cat: "Transport" },
    { jp: "ふね", reading: "船", en: "Ship / Boat", cat: "Transport" },
    { jp: "ちかてつ", reading: "地下鉄", en: "Subway", cat: "Transport" },
    { jp: "きっぷ", reading: "切符", en: "Ticket", cat: "Transport" },
    { jp: "みち", reading: "道", en: "Road / Way", cat: "Transport" },
    { jp: "はし", reading: "橋", en: "Bridge", cat: "Transport" },
    { jp: "しんごう", reading: "信号", en: "Traffic signal", cat: "Transport" },
    { jp: "こうさてん", reading: "交差点", en: "Intersection", cat: "Transport" },
    // Daily Items
    { jp: "でんわ", reading: "電話", en: "Telephone", cat: "Items" },
    { jp: "けいたい", reading: "携帯", en: "Mobile phone", cat: "Items" },
    { jp: "テレビ", reading: "", en: "Television", cat: "Items" },
    { jp: "ラジオ", reading: "", en: "Radio", cat: "Items" },
    { jp: "パソコン", reading: "", en: "Computer", cat: "Items" },
    { jp: "カメラ", reading: "", en: "Camera", cat: "Items" },
    { jp: "とけい", reading: "時計", en: "Clock / Watch", cat: "Items" },
    { jp: "かさ", reading: "傘", en: "Umbrella", cat: "Items" },
    { jp: "かぎ", reading: "鍵", en: "Key", cat: "Items" },
    { jp: "さいふ", reading: "財布", en: "Wallet", cat: "Items" },
    { jp: "はこ", reading: "箱", en: "Box", cat: "Items" },
    { jp: "ちず", reading: "地図", en: "Map", cat: "Items" },
    { jp: "しゃしん", reading: "写真", en: "Photo / Picture", cat: "Items" },
    { jp: "てがみ", reading: "手紙", en: "Letter", cat: "Items" },
    { jp: "はがき", reading: "葉書", en: "Postcard", cat: "Items" },
    { jp: "きって", reading: "切手", en: "Stamp (postage)", cat: "Items" },
    { jp: "ふうとう", reading: "封筒", en: "Envelope", cat: "Items" },
    { jp: "にもつ", reading: "荷物", en: "Luggage / Baggage", cat: "Items" },
    { jp: "おみやげ", reading: "お土産", en: "Souvenir", cat: "Items" },
    { jp: "プレゼント", reading: "", en: "Present / Gift", cat: "Items" },
    { jp: "メール", reading: "", en: "Email", cat: "Items" },
    { jp: "おかね", reading: "お金", en: "Money", cat: "Items" },
    { jp: "コップ", reading: "", en: "Cup / Glass", cat: "Items" },
    { jp: "さら", reading: "皿", en: "Plate / Dish", cat: "Items" },
    { jp: "はし", reading: "箸", en: "Chopsticks", cat: "Items" },
    { jp: "スプーン", reading: "", en: "Spoon", cat: "Items" },
    { jp: "フォーク", reading: "", en: "Fork", cat: "Items" },
    { jp: "ナイフ", reading: "", en: "Knife", cat: "Items" },
    // Clothes
    { jp: "ふく", reading: "服", en: "Clothes", cat: "Clothes" },
    { jp: "シャツ", reading: "", en: "Shirt", cat: "Clothes" },
    { jp: "ズボン", reading: "", en: "Pants / Trousers", cat: "Clothes" },
    { jp: "スカート", reading: "", en: "Skirt", cat: "Clothes" },
    { jp: "コート", reading: "", en: "Coat", cat: "Clothes" },
    { jp: "セーター", reading: "", en: "Sweater", cat: "Clothes" },
    { jp: "くつ", reading: "靴", en: "Shoes", cat: "Clothes" },
    { jp: "くつした", reading: "靴下", en: "Socks", cat: "Clothes" },
    { jp: "ぼうし", reading: "帽子", en: "Hat / Cap", cat: "Clothes" },
    { jp: "めがね", reading: "眼鏡", en: "Glasses", cat: "Clothes" },
    { jp: "ネクタイ", reading: "", en: "Necktie", cat: "Clothes" },
    // Colors
    { jp: "いろ", reading: "色", en: "Color", cat: "Colors" },
    { jp: "あか", reading: "赤", en: "Red", cat: "Colors" },
    { jp: "あお", reading: "青", en: "Blue", cat: "Colors" },
    { jp: "しろ", reading: "白", en: "White", cat: "Colors" },
    { jp: "くろ", reading: "黒", en: "Black", cat: "Colors" },
    { jp: "きいろ", reading: "黄色", en: "Yellow", cat: "Colors" },
    { jp: "みどり", reading: "緑", en: "Green", cat: "Colors" },
    { jp: "ちゃいろ", reading: "茶色", en: "Brown", cat: "Colors" },
    // Countries & Languages
    { jp: "にほん", reading: "日本", en: "Japan", cat: "Countries" },
    { jp: "ちゅうごく", reading: "中国", en: "China", cat: "Countries" },
    { jp: "かんこく", reading: "韓国", en: "South Korea", cat: "Countries" },
    { jp: "アメリカ", reading: "", en: "America / USA", cat: "Countries" },
    { jp: "イギリス", reading: "", en: "England / UK", cat: "Countries" },
    { jp: "フランス", reading: "", en: "France", cat: "Countries" },
    { jp: "ドイツ", reading: "", en: "Germany", cat: "Countries" },
    { jp: "オーストラリア", reading: "", en: "Australia", cat: "Countries" },
    { jp: "インド", reading: "", en: "India", cat: "Countries" },
    { jp: "パキスタン", reading: "", en: "Pakistan", cat: "Countries" },
    // Misc abstract nouns
    { jp: "しごと", reading: "仕事", en: "Work / Job", cat: "Misc" },
    { jp: "やすみ", reading: "休み", en: "Rest / Holiday / Absent", cat: "Misc" },
    { jp: "りょこう", reading: "旅行", en: "Travel / Trip", cat: "Misc" },
    { jp: "さんぽ", reading: "散歩", en: "Walk / Stroll", cat: "Misc" },
    { jp: "かいもの", reading: "買い物", en: "Shopping", cat: "Misc" },
    { jp: "パーティー", reading: "", en: "Party", cat: "Misc" },
    { jp: "えいが", reading: "映画", en: "Movie", cat: "Misc" },
    { jp: "おんがく", reading: "音楽", en: "Music", cat: "Misc" },
    { jp: "うた", reading: "歌", en: "Song", cat: "Misc" },
    { jp: "スポーツ", reading: "", en: "Sports", cat: "Misc" },
    { jp: "サッカー", reading: "", en: "Soccer", cat: "Misc" },
    { jp: "やきゅう", reading: "野球", en: "Baseball", cat: "Misc" },
    { jp: "しゅみ", reading: "趣味", en: "Hobby", cat: "Misc" },
    { jp: "ゲーム", reading: "", en: "Game", cat: "Misc" },
    { jp: "たんじょうび", reading: "誕生日", en: "Birthday", cat: "Misc" },
    { jp: "おまつり", reading: "お祭り", en: "Festival", cat: "Misc" },
    { jp: "びじゅつかん", reading: "美術館", en: "Art museum", cat: "Misc" },
    { jp: "じんじゃ", reading: "神社", en: "Shrine", cat: "Misc" },
    { jp: "おてら", reading: "お寺", en: "Temple", cat: "Misc" },
    { jp: "せかい", reading: "世界", en: "World", cat: "Misc" },
    { jp: "でんき", reading: "電気", en: "Electricity / Light", cat: "Misc" },
];
