// JLPT N5 Vocabulary — Part 4: Verbs (all ~100 N5 verbs), Adjectives, Adverbs, Greetings, Expressions
const VOCAB_VERBS = [
    // Group 1 (Godan / U-verbs)
    { jp: "あう", reading: "会う", en: "To meet", cat: "Verbs-G1" },
    { jp: "あそぶ", reading: "遊ぶ", en: "To play / hang out", cat: "Verbs-G1" },
    { jp: "あらう", reading: "洗う", en: "To wash", cat: "Verbs-G1" },
    { jp: "ある", reading: "", en: "To exist (inanimate)", cat: "Verbs-G1" },
    { jp: "あるく", reading: "歩く", en: "To walk", cat: "Verbs-G1" },
    { jp: "いう", reading: "言う", en: "To say / tell", cat: "Verbs-G1" },
    { jp: "いく", reading: "行く", en: "To go", cat: "Verbs-G1" },
    { jp: "いる", reading: "要る", en: "To need", cat: "Verbs-G1" },
    { jp: "うたう", reading: "歌う", en: "To sing", cat: "Verbs-G1" },
    { jp: "おく", reading: "置く", en: "To put / place", cat: "Verbs-G1" },
    { jp: "おくる", reading: "送る", en: "To send", cat: "Verbs-G1" },
    { jp: "おす", reading: "押す", en: "To push / press", cat: "Verbs-G1" },
    { jp: "おもう", reading: "思う", en: "To think", cat: "Verbs-G1" },
    { jp: "およぐ", reading: "泳ぐ", en: "To swim", cat: "Verbs-G1" },
    { jp: "おわる", reading: "終わる", en: "To end / finish", cat: "Verbs-G1" },
    { jp: "かう", reading: "買う", en: "To buy", cat: "Verbs-G1" },
    { jp: "かえる", reading: "帰る", en: "To return home", cat: "Verbs-G1" },
    { jp: "かかる", reading: "", en: "To take (time/money)", cat: "Verbs-G1" },
    { jp: "かく", reading: "書く", en: "To write", cat: "Verbs-G1" },
    { jp: "かす", reading: "貸す", en: "To lend", cat: "Verbs-G1" },
    { jp: "かぶる", reading: "", en: "To wear (on head)", cat: "Verbs-G1" },
    { jp: "きく", reading: "聞く", en: "To listen / hear / ask", cat: "Verbs-G1" },
    { jp: "きる", reading: "切る", en: "To cut", cat: "Verbs-G1" },
    { jp: "けす", reading: "消す", en: "To turn off / erase", cat: "Verbs-G1" },
    { jp: "こまる", reading: "困る", en: "To be troubled", cat: "Verbs-G1" },
    { jp: "さす", reading: "差す", en: "To hold (umbrella)", cat: "Verbs-G1" },
    { jp: "しる", reading: "知る", en: "To know", cat: "Verbs-G1" },
    { jp: "すう", reading: "吸う", en: "To smoke / breathe in", cat: "Verbs-G1" },
    { jp: "すむ", reading: "住む", en: "To live / reside", cat: "Verbs-G1" },
    { jp: "すわる", reading: "座る", en: "To sit down", cat: "Verbs-G1" },
    { jp: "たつ", reading: "立つ", en: "To stand up", cat: "Verbs-G1" },
    { jp: "つかう", reading: "使う", en: "To use", cat: "Verbs-G1" },
    { jp: "つく", reading: "着く", en: "To arrive", cat: "Verbs-G1" },
    { jp: "つくる", reading: "作る", en: "To make / create", cat: "Verbs-G1" },
    { jp: "とぶ", reading: "飛ぶ", en: "To fly / jump", cat: "Verbs-G1" },
    { jp: "とまる", reading: "止まる", en: "To stop", cat: "Verbs-G1" },
    { jp: "とる", reading: "撮る", en: "To take (photo)", cat: "Verbs-G1" },
    { jp: "とる", reading: "取る", en: "To take / get", cat: "Verbs-G1" },
    { jp: "ならう", reading: "習う", en: "To learn (from teacher)", cat: "Verbs-G1" },
    { jp: "ならぶ", reading: "並ぶ", en: "To line up", cat: "Verbs-G1" },
    { jp: "なくす", reading: "無くす", en: "To lose (something)", cat: "Verbs-G1" },
    { jp: "のぼる", reading: "登る", en: "To climb", cat: "Verbs-G1" },
    { jp: "のむ", reading: "飲む", en: "To drink", cat: "Verbs-G1" },
    { jp: "のる", reading: "乗る", en: "To ride / get on", cat: "Verbs-G1" },
    { jp: "はいる", reading: "入る", en: "To enter", cat: "Verbs-G1" },
    { jp: "はく", reading: "履く", en: "To wear (below waist)", cat: "Verbs-G1" },
    { jp: "はじまる", reading: "始まる", en: "To begin (intransitive)", cat: "Verbs-G1" },
    { jp: "はしる", reading: "走る", en: "To run", cat: "Verbs-G1" },
    { jp: "はたらく", reading: "働く", en: "To work", cat: "Verbs-G1" },
    { jp: "はなす", reading: "話す", en: "To speak / talk", cat: "Verbs-G1" },
    { jp: "はる", reading: "貼る", en: "To stick / paste", cat: "Verbs-G1" },
    { jp: "ひく", reading: "弾く", en: "To play (instrument)", cat: "Verbs-G1" },
    { jp: "まがる", reading: "曲がる", en: "To turn (direction)", cat: "Verbs-G1" },
    { jp: "まつ", reading: "待つ", en: "To wait", cat: "Verbs-G1" },
    { jp: "もつ", reading: "持つ", en: "To hold / have", cat: "Verbs-G1" },
    { jp: "もらう", reading: "", en: "To receive", cat: "Verbs-G1" },
    { jp: "やすむ", reading: "休む", en: "To rest / take day off", cat: "Verbs-G1" },
    { jp: "よぶ", reading: "呼ぶ", en: "To call (someone)", cat: "Verbs-G1" },
    { jp: "よむ", reading: "読む", en: "To read", cat: "Verbs-G1" },
    { jp: "わかる", reading: "分かる", en: "To understand", cat: "Verbs-G1" },
    { jp: "わたる", reading: "渡る", en: "To cross (road/bridge)", cat: "Verbs-G1" },
    // Group 2 (Ichidan / Ru-verbs)
    { jp: "あげる", reading: "", en: "To give (to someone)", cat: "Verbs-G2" },
    { jp: "あける", reading: "開ける", en: "To open", cat: "Verbs-G2" },
    { jp: "あびる", reading: "浴びる", en: "To shower / bathe", cat: "Verbs-G2" },
    { jp: "いる", reading: "居る", en: "To exist (animate)", cat: "Verbs-G2" },
    { jp: "いれる", reading: "入れる", en: "To put in / insert", cat: "Verbs-G2" },
    { jp: "おきる", reading: "起きる", en: "To wake up / get up", cat: "Verbs-G2" },
    { jp: "おしえる", reading: "教える", en: "To teach / tell", cat: "Verbs-G2" },
    { jp: "おぼえる", reading: "覚える", en: "To memorize", cat: "Verbs-G2" },
    { jp: "おりる", reading: "降りる", en: "To get off / descend", cat: "Verbs-G2" },
    { jp: "かける", reading: "", en: "To make a call / hang", cat: "Verbs-G2" },
    { jp: "かりる", reading: "借りる", en: "To borrow", cat: "Verbs-G2" },
    { jp: "きる", reading: "着る", en: "To wear (upper body)", cat: "Verbs-G2" },
    { jp: "しめる", reading: "閉める", en: "To close / shut", cat: "Verbs-G2" },
    { jp: "たべる", reading: "食べる", en: "To eat", cat: "Verbs-G2" },
    { jp: "つける", reading: "", en: "To turn on / attach", cat: "Verbs-G2" },
    { jp: "でかける", reading: "出かける", en: "To go out", cat: "Verbs-G2" },
    { jp: "できる", reading: "", en: "To be able to / can", cat: "Verbs-G2" },
    { jp: "でる", reading: "出る", en: "To go out / exit / appear", cat: "Verbs-G2" },
    { jp: "とめる", reading: "止める", en: "To stop (something)", cat: "Verbs-G2" },
    { jp: "ならべる", reading: "並べる", en: "To arrange / line up", cat: "Verbs-G2" },
    { jp: "ねる", reading: "寝る", en: "To sleep / go to bed", cat: "Verbs-G2" },
    { jp: "みせる", reading: "見せる", en: "To show", cat: "Verbs-G2" },
    { jp: "みる", reading: "見る", en: "To see / watch / look", cat: "Verbs-G2" },
    { jp: "わすれる", reading: "忘れる", en: "To forget", cat: "Verbs-G2" },
    // Group 3 (Irregular)
    { jp: "する", reading: "", en: "To do", cat: "Verbs-G3" },
    { jp: "くる", reading: "来る", en: "To come", cat: "Verbs-G3" },
    { jp: "べんきょうする", reading: "勉強する", en: "To study", cat: "Verbs-G3" },
    { jp: "しごとする", reading: "仕事する", en: "To work (job)", cat: "Verbs-G3" },
    { jp: "りょこうする", reading: "旅行する", en: "To travel", cat: "Verbs-G3" },
    { jp: "さんぽする", reading: "散歩する", en: "To take a walk", cat: "Verbs-G3" },
    { jp: "せんたくする", reading: "洗濯する", en: "To do laundry", cat: "Verbs-G3" },
    { jp: "そうじする", reading: "掃除する", en: "To clean", cat: "Verbs-G3" },
    { jp: "りょうりする", reading: "料理する", en: "To cook", cat: "Verbs-G3" },
    { jp: "かいものする", reading: "買い物する", en: "To go shopping", cat: "Verbs-G3" },
    { jp: "でんわする", reading: "電話する", en: "To make a phone call", cat: "Verbs-G3" },
    { jp: "コピーする", reading: "", en: "To copy", cat: "Verbs-G3" },
];

const VOCAB_ADJECTIVES = [
    // i-adjectives
    { jp: "あたたかい", reading: "暖かい", en: "Warm", cat: "i-adj" },
    { jp: "あつい", reading: "暑い", en: "Hot (weather)", cat: "i-adj" },
    { jp: "あつい", reading: "熱い", en: "Hot (things)", cat: "i-adj" },
    { jp: "あぶない", reading: "危ない", en: "Dangerous", cat: "i-adj" },
    { jp: "あまい", reading: "甘い", en: "Sweet", cat: "i-adj" },
    { jp: "いい/よい", reading: "良い", en: "Good", cat: "i-adj" },
    { jp: "いそがしい", reading: "忙しい", en: "Busy", cat: "i-adj" },
    { jp: "いたい", reading: "痛い", en: "Painful / Hurts", cat: "i-adj" },
    { jp: "うるさい", reading: "", en: "Noisy / Annoying", cat: "i-adj" },
    { jp: "おいしい", reading: "美味しい", en: "Delicious / Tasty", cat: "i-adj" },
    { jp: "おおい", reading: "多い", en: "Many / Much", cat: "i-adj" },
    { jp: "おおきい", reading: "大きい", en: "Big / Large", cat: "i-adj" },
    { jp: "おそい", reading: "遅い", en: "Late / Slow", cat: "i-adj" },
    { jp: "おもい", reading: "重い", en: "Heavy", cat: "i-adj" },
    { jp: "おもしろい", reading: "面白い", en: "Interesting / Funny", cat: "i-adj" },
    { jp: "かるい", reading: "軽い", en: "Light (weight)", cat: "i-adj" },
    { jp: "かわいい", reading: "可愛い", en: "Cute", cat: "i-adj" },
    { jp: "きたない", reading: "汚い", en: "Dirty", cat: "i-adj" },
    { jp: "さむい", reading: "寒い", en: "Cold (weather)", cat: "i-adj" },
    { jp: "すくない", reading: "少ない", en: "Few / Little", cat: "i-adj" },
    { jp: "すずしい", reading: "涼しい", en: "Cool (weather)", cat: "i-adj" },
    { jp: "せまい", reading: "狭い", en: "Narrow / Cramped", cat: "i-adj" },
    { jp: "たかい", reading: "高い", en: "Expensive / Tall / High", cat: "i-adj" },
    { jp: "たのしい", reading: "楽しい", en: "Fun / Enjoyable", cat: "i-adj" },
    { jp: "ちいさい", reading: "小さい", en: "Small / Little", cat: "i-adj" },
    { jp: "ちかい", reading: "近い", en: "Near / Close", cat: "i-adj" },
    { jp: "つまらない", reading: "", en: "Boring", cat: "i-adj" },
    { jp: "つめたい", reading: "冷たい", en: "Cold (things/drinks)", cat: "i-adj" },
    { jp: "とおい", reading: "遠い", en: "Far / Distant", cat: "i-adj" },
    { jp: "ながい", reading: "長い", en: "Long", cat: "i-adj" },
    { jp: "はやい", reading: "早い", en: "Early", cat: "i-adj" },
    { jp: "はやい", reading: "速い", en: "Fast / Quick", cat: "i-adj" },
    { jp: "ひくい", reading: "低い", en: "Low / Short (height)", cat: "i-adj" },
    { jp: "ひろい", reading: "広い", en: "Wide / Spacious", cat: "i-adj" },
    { jp: "ふるい", reading: "古い", en: "Old (things)", cat: "i-adj" },
    { jp: "ほしい", reading: "欲しい", en: "Want (something)", cat: "i-adj" },
    { jp: "まずい", reading: "", en: "Bad tasting", cat: "i-adj" },
    { jp: "みじかい", reading: "短い", en: "Short (length)", cat: "i-adj" },
    { jp: "むずかしい", reading: "難しい", en: "Difficult / Hard", cat: "i-adj" },
    { jp: "やさしい", reading: "優しい", en: "Kind / Gentle", cat: "i-adj" },
    { jp: "やさしい", reading: "易しい", en: "Easy / Simple", cat: "i-adj" },
    { jp: "やすい", reading: "安い", en: "Cheap / Inexpensive", cat: "i-adj" },
    { jp: "わかい", reading: "若い", en: "Young", cat: "i-adj" },
    { jp: "わるい", reading: "悪い", en: "Bad", cat: "i-adj" },
    { jp: "あたらしい", reading: "新しい", en: "New", cat: "i-adj" },
    { jp: "あかるい", reading: "明るい", en: "Bright / Cheerful", cat: "i-adj" },
    { jp: "くらい", reading: "暗い", en: "Dark", cat: "i-adj" },
    { jp: "からい", reading: "辛い", en: "Spicy / Hot", cat: "i-adj" },
    // na-adjectives
    { jp: "きれい", reading: "", en: "Beautiful / Clean", cat: "na-adj" },
    { jp: "しずか", reading: "静か", en: "Quiet / Silent", cat: "na-adj" },
    { jp: "にぎやか", reading: "賑やか", en: "Lively / Bustling", cat: "na-adj" },
    { jp: "げんき", reading: "元気", en: "Healthy / Energetic", cat: "na-adj" },
    { jp: "ひま", reading: "暇", en: "Free (time)", cat: "na-adj" },
    { jp: "じょうず", reading: "上手", en: "Skillful / Good at", cat: "na-adj" },
    { jp: "へた", reading: "下手", en: "Unskillful / Bad at", cat: "na-adj" },
    { jp: "すき", reading: "好き", en: "Like / Favorite", cat: "na-adj" },
    { jp: "だいすき", reading: "大好き", en: "Love / Really like", cat: "na-adj" },
    { jp: "きらい", reading: "嫌い", en: "Dislike / Hate", cat: "na-adj" },
    { jp: "たいへん", reading: "大変", en: "Tough / Terrible / Very", cat: "na-adj" },
    { jp: "べんり", reading: "便利", en: "Convenient / Handy", cat: "na-adj" },
    { jp: "ふべん", reading: "不便", en: "Inconvenient", cat: "na-adj" },
    { jp: "ゆうめい", reading: "有名", en: "Famous", cat: "na-adj" },
    { jp: "しんせつ", reading: "親切", en: "Kind / Helpful", cat: "na-adj" },
    { jp: "だいじ", reading: "大事", en: "Important / Valuable", cat: "na-adj" },
    { jp: "だいじょうぶ", reading: "大丈夫", en: "Okay / All right", cat: "na-adj" },
    { jp: "いろいろ", reading: "色々", en: "Various", cat: "na-adj" },
    { jp: "たいせつ", reading: "大切", en: "Important / Precious", cat: "na-adj" },
    { jp: "じょうぶ", reading: "丈夫", en: "Durable / Healthy", cat: "na-adj" },
    { jp: "ハンサム", reading: "", en: "Handsome", cat: "na-adj" },
];

const VOCAB_ADVERBS_EXP = [
    { jp: "とても", reading: "", en: "Very / Really", cat: "Adverbs" },
    { jp: "たいへん", reading: "大変", en: "Very (formal)", cat: "Adverbs" },
    { jp: "あまり", reading: "", en: "Not very (+ neg.)", cat: "Adverbs" },
    { jp: "ぜんぜん", reading: "全然", en: "Not at all (+ neg.)", cat: "Adverbs" },
    { jp: "いつも", reading: "", en: "Always", cat: "Adverbs" },
    { jp: "よく", reading: "", en: "Often / Well", cat: "Adverbs" },
    { jp: "ときどき", reading: "時々", en: "Sometimes", cat: "Adverbs" },
    { jp: "いつ", reading: "", en: "When", cat: "Adverbs" },
    { jp: "たくさん", reading: "", en: "Many / A lot", cat: "Adverbs" },
    { jp: "すこし", reading: "少し", en: "A little", cat: "Adverbs" },
    { jp: "ちょっと", reading: "", en: "A bit (casual)", cat: "Adverbs" },
    { jp: "もう", reading: "", en: "Already / More", cat: "Adverbs" },
    { jp: "まだ", reading: "", en: "Not yet / Still", cat: "Adverbs" },
    { jp: "もっと", reading: "", en: "More", cat: "Adverbs" },
    { jp: "はじめて", reading: "初めて", en: "For the first time", cat: "Adverbs" },
    { jp: "ゆっくり", reading: "", en: "Slowly / Leisurely", cat: "Adverbs" },
    { jp: "すぐ", reading: "", en: "Soon / Right away", cat: "Adverbs" },
    { jp: "たぶん", reading: "多分", en: "Probably / Maybe", cat: "Adverbs" },
    { jp: "ほんとうに", reading: "本当に", en: "Really / Truly", cat: "Adverbs" },
    { jp: "いちばん", reading: "一番", en: "The most / Number one", cat: "Adverbs" },
    { jp: "だんだん", reading: "", en: "Gradually", cat: "Adverbs" },
    { jp: "まっすぐ", reading: "", en: "Straight ahead", cat: "Adverbs" },
    { jp: "いっしょに", reading: "一緒に", en: "Together", cat: "Adverbs" },
];

const VOCAB_EXPRESSIONS = [
    { jp: "おはようございます", reading: "", en: "Good morning (polite)", cat: "Greetings" },
    { jp: "こんにちは", reading: "", en: "Hello / Good afternoon", cat: "Greetings" },
    { jp: "こんばんは", reading: "", en: "Good evening", cat: "Greetings" },
    { jp: "おやすみなさい", reading: "", en: "Good night", cat: "Greetings" },
    { jp: "さようなら", reading: "", en: "Goodbye", cat: "Greetings" },
    { jp: "ありがとうございます", reading: "", en: "Thank you (polite)", cat: "Greetings" },
    { jp: "どういたしまして", reading: "", en: "You're welcome", cat: "Greetings" },
    { jp: "すみません", reading: "", en: "Excuse me / I'm sorry", cat: "Greetings" },
    { jp: "ごめんなさい", reading: "", en: "I'm sorry (apology)", cat: "Greetings" },
    { jp: "はじめまして", reading: "", en: "Nice to meet you", cat: "Greetings" },
    { jp: "よろしくおねがいします", reading: "", en: "Pleased to meet you / Please", cat: "Greetings" },
    { jp: "いただきます", reading: "", en: "Before eating (gratitude)", cat: "Greetings" },
    { jp: "ごちそうさまでした", reading: "", en: "After eating (thanks for meal)", cat: "Greetings" },
    { jp: "ただいま", reading: "", en: "I'm home", cat: "Greetings" },
    { jp: "おかえりなさい", reading: "", en: "Welcome home", cat: "Greetings" },
    { jp: "いってきます", reading: "", en: "I'm leaving (home)", cat: "Greetings" },
    { jp: "いってらっしゃい", reading: "", en: "Have a safe trip", cat: "Greetings" },
    { jp: "おめでとうございます", reading: "", en: "Congratulations", cat: "Greetings" },
    { jp: "おねがいします", reading: "", en: "Please (request)", cat: "Greetings" },
    { jp: "ちょっとまってください", reading: "", en: "Please wait a moment", cat: "Expressions" },
    { jp: "もういちど", reading: "もう一度", en: "One more time", cat: "Expressions" },
    { jp: "だいじょうぶです", reading: "大丈夫です", en: "It's okay / I'm fine", cat: "Expressions" },
    { jp: "わかりました", reading: "分かりました", en: "I understood", cat: "Expressions" },
    { jp: "わかりません", reading: "分かりません", en: "I don't understand", cat: "Expressions" },
    { jp: "しりません", reading: "知りません", en: "I don't know", cat: "Expressions" },
    { jp: "そうですか", reading: "", en: "Is that so? / Really?", cat: "Expressions" },
    { jp: "そうですね", reading: "", en: "That's right / I agree", cat: "Expressions" },
    { jp: "いくらですか", reading: "", en: "How much is it?", cat: "Expressions" },
    { jp: "なんですか", reading: "何ですか", en: "What is it?", cat: "Expressions" },
    { jp: "どうぞ", reading: "", en: "Please (go ahead)", cat: "Expressions" },
    { jp: "きをつけて", reading: "気をつけて", en: "Be careful / Take care", cat: "Expressions" },
    // Pronouns & Demonstratives
    { jp: "これ", reading: "", en: "This (near speaker)", cat: "Pronouns" },
    { jp: "それ", reading: "", en: "That (near listener)", cat: "Pronouns" },
    { jp: "あれ", reading: "", en: "That (far from both)", cat: "Pronouns" },
    { jp: "この", reading: "", en: "This ~ (+ noun)", cat: "Pronouns" },
    { jp: "その", reading: "", en: "That ~ (+ noun)", cat: "Pronouns" },
    { jp: "あの", reading: "", en: "That ~ over there (+ noun)", cat: "Pronouns" },
    { jp: "ここ", reading: "", en: "Here", cat: "Pronouns" },
    { jp: "そこ", reading: "", en: "There", cat: "Pronouns" },
    { jp: "あそこ", reading: "", en: "Over there", cat: "Pronouns" },
    { jp: "どこ", reading: "", en: "Where", cat: "Pronouns" },
    { jp: "どれ", reading: "", en: "Which one", cat: "Pronouns" },
    { jp: "どの", reading: "", en: "Which ~ (+ noun)", cat: "Pronouns" },
    { jp: "だれ", reading: "誰", en: "Who", cat: "Pronouns" },
    { jp: "なに/なん", reading: "何", en: "What", cat: "Pronouns" },
    { jp: "どう", reading: "", en: "How", cat: "Pronouns" },
    { jp: "どうして", reading: "", en: "Why", cat: "Pronouns" },
    { jp: "どのくらい", reading: "", en: "How long / How much", cat: "Pronouns" },
    // Position words
    { jp: "うえ", reading: "上", en: "Up / Above / On", cat: "Position" },
    { jp: "した", reading: "下", en: "Down / Below / Under", cat: "Position" },
    { jp: "なか", reading: "中", en: "Inside / Middle", cat: "Position" },
    { jp: "そと", reading: "外", en: "Outside", cat: "Position" },
    { jp: "まえ", reading: "前", en: "Front / Before", cat: "Position" },
    { jp: "うしろ", reading: "後ろ", en: "Behind / Back", cat: "Position" },
    { jp: "ひだり", reading: "左", en: "Left", cat: "Position" },
    { jp: "みぎ", reading: "右", en: "Right", cat: "Position" },
    { jp: "となり", reading: "隣", en: "Next to", cat: "Position" },
    { jp: "あいだ", reading: "間", en: "Between", cat: "Position" },
    { jp: "ちかく", reading: "近く", en: "Nearby", cat: "Position" },
    { jp: "むこう", reading: "向こう", en: "Over there / Opposite side", cat: "Position" },
    // Counters
    { jp: "ひとつ", reading: "一つ", en: "One (general)", cat: "Counters" },
    { jp: "ふたつ", reading: "二つ", en: "Two (general)", cat: "Counters" },
    { jp: "みっつ", reading: "三つ", en: "Three (general)", cat: "Counters" },
    { jp: "よっつ", reading: "四つ", en: "Four (general)", cat: "Counters" },
    { jp: "いつつ", reading: "五つ", en: "Five (general)", cat: "Counters" },
    { jp: "むっつ", reading: "六つ", en: "Six (general)", cat: "Counters" },
    { jp: "ななつ", reading: "七つ", en: "Seven (general)", cat: "Counters" },
    { jp: "やっつ", reading: "八つ", en: "Eight (general)", cat: "Counters" },
    { jp: "ここのつ", reading: "九つ", en: "Nine (general)", cat: "Counters" },
    { jp: "とお", reading: "十", en: "Ten (general)", cat: "Counters" },
    { jp: "いくつ", reading: "", en: "How many (general)", cat: "Counters" },
    { jp: "ひとり", reading: "一人", en: "One person", cat: "Counters" },
    { jp: "ふたり", reading: "二人", en: "Two people", cat: "Counters" },
];
